enum ActionType {
  GET_PRODUCTS = "GET_PRODUCTS",
  CREATE_PRODUCT = "CREATE_PRODUCT",
  DELETE_PRODUCT = "DELETE_PRODUCT",
  UPDATE_PRODUCT = "UPDATE_PRODUCT",
  CHOSED_PRODUCT = "CHOSED_PRODUCT",
}

export { ActionType };
